sometimes main can exit 2
FAIL	github.com/luathn/gotestsum/testjson/internal/badmain	0.001s
-test.shuffle 123456
ok  	github.com/luathn/gotestsum/testjson/internal/good	0.020s
-test.shuffle 123456
FAIL
FAIL	github.com/luathn/gotestsum/testjson/internal/parallelfails	0.020s
-test.shuffle 123456
FAIL
FAIL	github.com/luathn/gotestsum/testjson/internal/withfails	0.020s
